---
  title: "Extra Credit"
---

Throughout the course, there will be multiple opportunities for extra credit. I’ll add more as we go along, but here are the first few. Each extra credit opportunity below can be worth 5% of your total grade.

**Be Your Own Nate Silver** It’s an election year. Given that you’re in this class, I’m sure you are following along at http://fivethirtyeight.com/ and their model with great interest. You’re also, of course, listening to their elections podcast – and definitely the Friday special edition on how they build their model. I want you to forecast one or more elections.  You can find poll data using the pollstR package (https://cran.r-project.org/web/packages/pollstR/vignettes/introduction.html) or other sources (http://is-r.tumblr.com/post/36059986744/gathering-realclearpolitics-polling-trends-with) and there are plenty of other data sources out there (http://guides.library.harvard.edu/c.php?g=310717&p=2072692 as just a start – Google around). For this extra credit, 5 points for getting the correct answer, 5 extra points for explicitly stating the confidence of your estimates, and 5 points for a clear explanation of the methodology. 1 point for each thing you do beyond a weighted average of polls. Because, come on, that’s easy. Scored out of 16. So, theoretically, you could get extra credit on your extra credit.  

**Become a Git Addict** Make a github repository for all of your work in this class! Structure it well, with a homework, lab, and project section. Inside of each should be a well structured set of directories (we'll talk about this). To get this repo up and running,  This requires learning git and github. There are numerous tutorials on how to do so both as web pages and on youtube (e.g.,http://happygitwithr.com/ which is one of my favs) - so find what works for you. I’ll also host a mini-tutorial sometime in the first few weeks. +1 point on each homework that is submitted as a link. +10 if you make your repo into a github.io website that is fully navigable (requires learning some webpage building in R)

**Join the Conversation** There are a wealth of great conversations out there about data science both in and out of biology. Starting to listen to the conversation will enable you to keep abreast of how the field is developing, and enable you to learn toolsets that will put you a cut above your colleagues as you consider new and sophisticated analyses. I’d recommend checking out sites list http://www.r-bloggers.com/ daily, listening to podcasts such as Not So Standard Deviations https://itunes.apple.com/us/podcast/not-so-standard-deviations/ or following different data science/biology luminaries (such as [@hadleywickham](http://twitter.com/hadleywickham), [@_inundata](http://twitter.com/_inundata), [@rdpeng](http://twitter.com/rdpeng), [@hspter](http://twitter.com/hspter), [@kara_woo](http://twitter.com/kara_woo), [@sckottie](http://twitter.com/sckottie), and more). I've also made a full list at https://twitter.com/jebyrnes/lists/stats-r-on-twitter. There are a ton of other blogs and people who are relevant to what you are doing for your research, so look around! Each class, I’ll try and give an opportunity to share neat things you’ve seen in the ether. +1 for each contribution you make to the class. +10 if you end up at [ROpenSci](http://unconf.ropensci.org/).

**Engage in Data Science at UMB** This is a gimme. So, I've started a a UMB R Users Group that has a slack channel at https://umbrug.slack.com/. Join it and the biol607 channel (where we can talk live) for +3 points on your final grade. Also, there is a Stats Snack group run by the psych department. It meets Tuesdays in Science S4-6401 from 12-1. +5 for attending!