install.packages("rmarkdown")
install.packages("quarto")
install.packages("remotes")
install.packages("devtools")
install.packages("tidyverse")
install.packages("patchwork")
install.packages("gridExtra")
install.packages("gganimate")
install.packages("ggthemes")
install.packages("wesanderson")
install.packages("ggfortify")
install.packages("xaringan")
install.packages(c("car", "emmeans", "multcompView", "contrast"))
install.packages(c("janitor", "skimr", "lubridate", "visdat", "readr", "readxl"))
install.packages(c("ggplot2", "ggridges", "palmerpenguins", "ggdist"))
install.packages(c("MASS", "profileModel", "bbmle", "rsample"))
install.packages("QuantPsyc")
install.packages("brms")
install.packages(c("bayesplot", "loo"))
install.packages(c("rstanarm", "arm", "rethinking"))
install.packages("broom.mixed")
install.packages("DHARMa")
install.packages("tidybayes")
install.packages("MCMCglmm")
install.packages("coda")
install.packages("easystats")
install.packages("car")
install.packages("betareg")
install.packages("glmmTMB")
install.packages(c("AICcmodavg", "MuMIn", "modelr"))
install.packages("visreg")
install.packages("usethis")
install.packages("mvtnorm")
install.packages("mnormt")
install.packages("kableExtra")
install.packages("magrittr")
install.packages("tidymodels")
install.packages("flextable")
install.packages("datapasta")
